name: Build all on macos
on: [push]
jobs:
  clone-to-OF_ROOT:
    runs-on: [self-hosted, macOS]
    environment: RUNNER-MACOS
    steps:
      - name: remove existing clone
        working-directory: ${{ vars.ADDONS_DIR }}
        run: |
          pwd
          #echo "the commit that dispatched this job-- ${GITHUB_SHA}"
          if [ -d ofxEmotiBit ]; then
            echo "Directory exists."
            rm -rf ofxEmotiBit
            echo "clone removed"
          else
            echo "Directory does not already exist"
          fi
      - name: checkout repository
        uses: actions/checkout@v4  
      - name: move fresh clone to OF_ROOT
        run: cp -r ../$(echo ${{ github.repository }} | cut -d '/' -f 2) ${{ vars.ADDONS_DIR }}
  build-oscilloscope:
    needs: clone-to-OF_ROOT
    runs-on: [self-hosted, macOS]
    environment: RUNNER-MACOS
    steps: 
      - name: build using xcode
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          cd EmotiBitOscilloscope
          xcodebuild -project EmotiBitOscilloscope.xcodeproj -scheme Release-x86_64
  build-dataparser:
    needs: clone-to-OF_ROOT
    runs-on: [self-hosted, macOS]
    environment: RUNNER-MACOS
    steps: 
      - name: build using xcode
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          cd EmotiBitDataParser
          xcodebuild -project EmotiBitDataParser.xcodeproj -scheme Release
  build-firmwareinstaller:
    needs: clone-to-OF_ROOT
    runs-on: [self-hosted, macOS]
    environment: RUNNER-MACOS
    steps: 
      - name: build using xcode
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          cd EmotiBitFirmwareInstaller
          xcodebuild -project EmotiBitFirmwareInstaller.xcodeproj -scheme Release
