name: Linux workflows
on: [push]
jobs:
  clone-to-OF_ROOT:
    runs-on: [self-hosted, Linux]
    environment: RUNNER-LINUX
    steps:
      - name: remove existing clone
        working-directory: ${{ vars.ADDONS_DIR }}
        run: |
          pwd
          #echo "the commit that dispatched this job-- ${GITHUB_SHA}"
          if [ -d ofxEmotiBit ]; then
            echo "Directory exists."
            rm -rf ofxEmotiBit
            echo "clone removed"
          else
            echo "Directory does not already exist"
          fi
      - name: checkout repository
        uses: actions/checkout@v4  
      - name: move fresh clone to OF_ROOT
        run: cp -r ../$(echo ${{ github.repository }} | cut -d '/' -f 2) ${{ vars.ADDONS_DIR }}
  build-oscilloscope:
    needs: clone-to-OF_ROOT
    uses: ./.github/workflows/reusable-workflow-build-oscilloscope-linux.yml

  build-dataparser:
    needs: clone-to-OF_ROOT
    uses: ./.github/workflows/reusable-workflow-build-dataParser-linux.yml
  
  test-dataParser:
    needs: build-dataparser
    uses: ./.github/workflows/reusable-workflow-test-dataParser-linux.yml
