name: Build Oscilloscope on Linux (reusable)
on:
  workflow_call:
jobs:
  build-oscilloscope-linux:
    runs-on: [self-hosted, Linux]
    environment: RUNNER-LINUX
    steps: 
      - name: build using make
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          cd EmotiBitOscilloscope
          make -j