name: DataParser tests
#on: [push]
on:
  #workflow_dispatch:
  workflow_run:
    workflows: ["Build all on linux"]
    types:
     - completed
jobs:
  test-ParserOutput:
    runs-on: [self-hosted, Linux]
    environment: RUNNER-LINUX
    steps:
      - name: find untested typetags
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        env:
          ENV_OFXEMOTIBIT_DIR: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo pwd
          bash tests/EmotiBitDataParser/find_unused_typetags/run_test.sh -d ENV_OFXEMOTIBIT_DIR

      - name: check parsed file hash
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        env:
          ENV_OFXEMOTIBIT_DIR: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          bash tests/EmotiBitDataParser/check_parsed_data/run_test.sh -d ENV_OFXEMOTIBIT_DIR

