name: DataParser tests
on: [push]
# on:
  #workflow_dispatch:
  # workflow_run:
  #   workflows: ["Build all on linux"]
  #   types:
  #    - completed
jobs:
  test-ParserOutput:
    runs-on: [self-hosted, Linux]
    environment: RUNNER-LINUX
    steps:
      - name: run parser on sample data
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          bash tests/EmotiBitDataParser/test-0_parser_output/run_test.sh
      - name: find untested typetags
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          bash tests/EmotiBitDataParser/find_missing_typetags.sh
      - name: check parsed file hash
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          bash tests/EmotiBitDataParser/test-1_check_parsed_data/run_test.sh
