name: DataParser tests
on: [push]
# on:
  #workflow_dispatch:
  # workflow_run:
  #   workflows: ["Build all on linux"]
  #   types:
  #    - completed
jobs:
  test-ParserOutput:
    runs-on: [self-hosted, Linux]
    environment: RUNNER-LINUX
    steps:
      - name: run parser on sample data
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          ./EmotiBitDataParser/bin/EmotiBitDataParser "${{ vars.OFXEMOTIBIT_DIR }}/tests/EmotiBitDataParser/sample_data/2025-03-20_12-09-40-822726.csv"
      - name: find untested typetags
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          bash tests/EmotiBitDataParser/find-missing-typetags.sh
      - name: check parsed file hash
        working-directory: ${{ vars.OFXEMOTIBIT_DIR }}
        run: |
          echo "current working directory" && pwd
          cd tests/EmotiBitDataParser/test-0_parser_output
          bash md5_check.sh